### PR TITLE
guides: Refine UEFI guide for R1/beta3

### PR DESCRIPTION
**Pull request by kallisti5**

### CODE REVIEW

**Comment by kallisti5** [comment]
updates the guides to reference the bootloader now available on the filesystem. Fix version references.  Expand section on using 3rd party bootloaders to start Haiku

**Comment by jt15s** [comment]
Could one of the repo maintainers see if this is ready to merge? Thanks in advance!

**Comment by leavengood** [comment]
I looked at it but figured we would wait until the Beta 3 release since it mentions it.

**Comment by jt15s** [comment]
@leavengood Ah ok. Yeah, it's better to wait until the Beta3 release to merge it.

**Comment by jt15s** [comment]
Since Beta3 has been released, could someone please merge this? Thanks!

**Pull request merged**
