### PR TITLE
GSoC 2017 3D Hardware Acceleration Weekly Report 1

### PR DESCRIPTION
**Pull request by vivek-roy**
Weekly Report 1 for the GSoC 2017 Project: 3D Hardware Acceleration in Haiku.
Please Check @DeweyTaylor and @kallisti5

### CODE REVIEW

**Comment by kallisti5** [comment]
Looks great to me! Nice write-up.

**Comment by pulkomandy** [comment]
Good report, a link to the git repo where you are working on this would be nice. If we can reach one of our sysadmins, he could add it to the IRC/mailing list notification bots, too (if you want everyone to be notified of all your changes, that is).

**Comment by DeweyTaylor** [comment]
Looks great, Vivek.

Adrien, we're working out of a fork I created on github which I added
Vivek as a contributor on. The link is here:
https://github.com/DeweyTaylor/haiku_drm and as far as adding commits
to a mailing list bot, that's up to you guys but he and I will both
probably be committing to it (Vivek more than I of course, but I may
need to step in on occassion). Speaking of which, if you or Alex or
whoever think they might also need to be contributors, let me know and
I can add you.

**Comment by vivek-roy** [comment]
PulkoMandy, Duggan has a fork of haiku/haiku and has added me as a collaborator. In his fork he has imported the work done by hamishm (https://github.com/hamishm/haiku-drm).
I have made my own fork of haiku/haiku where again I added Duggan as a collaborator, but this time I am starting with a clean Haiku fork and adding the required files one by one, either from hamishm's work or from DragonflyBSD's sources (with changes, of-course).
The link to my fork : https://github.com/vivek-roy/haiku
I will add these links to the post and create another pull request in a couple of hours.

**Comment by vivek-roy** [comment]
PS: I have a separate branch named "drm" in my fork where I am doing all my work (started doing)

**Comment by vivek-roy** [comment]
Suggested changes made. Please check

**Pull request merged**
