### PR TITLE
[GSoC 2024]: Update Menu Bar In Find Panel Blog Post

### PR DESCRIPTION
**Pull request by Calisto-Mathias**
This PR consists of my blog post on my latest change to the Find Panel. This is the first set of changes to the Find Panel.

### CODE REVIEW

**Review by humdingerb — COMMENTED** [review]
What are these "Zone.Identifier" files? Never seen those before... Please remove.
It may be useful to link to the Gerrit change that's reviewing the discribed changes.

**Comment by korli** [comment]
> What are these "Zone.Identifier" files? Never seen those before... Please remove. It may be useful to link to the Gerrit change that's reviewing the discribed changes.

"Zone.Identifier" files removed.

**Comment by mmuman** [comment]
[These are actually NTFS alternate data streams](https://www.digital-detective.net/forensic-analysis-of-zone-identifier-stream/) (some form of attributes) used on Windows to indicate the origin of downloaded files for security reasons. I suppose they are copied as separate files when moving things around.

**Comment by humdingerb** [comment]
Count on old Windows to mess things up...
Thanks for fixing this, Korli.
@nielx , since you're Major Mentor, ready for march^W merge, sir?

**Pull request merged**
