### PR TITLE
Update uefi_booting.md

### PR DESCRIPTION
**Pull request by uberjoker**
Small edits to the UEFI Booting Haiku user guides page for clarity.

### CODE REVIEW

**Comment by pulkomandy** [comment]
Thanks :)

**Comment by korli** [comment]
At the moment, the EFI loader always prints "no boot path found, scan for all partitions...", then asks the user to select the boot partition on the SSD. Is there a way to pass the boot partition yet?

**Comment by pulkomandy** [comment]
I don't have this problem on my system, it finds the partition for me. But I don't know which version I'm using exactly, it's a few months older.

There is no way to pass the boot partition because in EFI case, there is no boot partition defined when the bootloader is loaded. The loader is loaded from the EFI system partition without having to select a specific Haiku boot partition.

We could store a partition path in an EFI variable, I think this is how other OS do it. Or maybe we can put some flag in the GPT header of the partition to mark it bootable?

**Comment by korli** [comment]
The GPT partition type was incorrect. After changing to 42465331-3BA3-10F1-802A-4861696B7521 for BFS, the loader found the partition. If more than one BFS partition is present, I suppose it has to be selected manually in the haiku loader.

**Comment by uberjoker** [comment]
> At the moment, the EFI loader always prints "no boot path found, scan for all partitions...", then asks the user to select the boot partition on the SSD. Is there a way to pass the boot partition yet?

> The GPT partition type was incorrect. After changing to 42465331-3BA3-10F1-802A-4861696B7521 for BFS, the loader found the partition. If more than one BFS partition is present, I suppose it has to be selected manually in the haiku loader.

I was seeing exactly the same issue on my install. After reading @korli 's comments, I checked my setup. For some reason, the Haiku partition type was set to Microsoft basic Data, and I had to manually select the partition each time on boot up. I too manually changed the type to Haiku BFS using fdisk and it's all fixed now.

The Haiku installer reformats the partition during install I think - maybe something there is not setting up the type correctly?

**Comment by pulkomandy** [comment]
The partition type is not erased by reformatting, only if you delete and recreate the partition in DriveSetup.

We should add an option in DriveSetup to change the partition type for GPT partition tables, if not already possible, and maybe the Installer should check and warn about it too.

**Comment by korli** [comment]
Looks like a known issue:
see https://dev.haiku-os.org/ticket/17050  https://dev.haiku-os.org/ticket/6287 https://dev.haiku-os.org/ticket/14839

**Comment by korli** [comment]
The gpt partition type can now be changed in Drivesetup.

**Pull request merged**
