### PR TITLE
Updated installation guide

### PR DESCRIPTION
**Pull request by humdingerb**
* Updated screenshots with current system font and GUI changes to
  FirstBootPrompt, DriveSetup, BootOptions.
* Use user guide screenshot style, i.e. 10pt fonts.
* Updated text to reflect those GUI changes (e.g. initialize <->
  format).
* Removed steps that just depict "Are you sure" alerts. Those don't
  need elaborate explanations with a screenshot.
* Update URLs to use https.
* Add links to the user guide / welcome page.

### CODE REVIEW

**Review by jt15s — APPROVED** [review]

**Comment by diversys** [comment]
I still think that fonts in Haiku look badly at 10pt fonts :(

**Comment by waddlesplash** [comment]
Perhaps this belongs in the User Guide, or Welcome manual?

**Comment by humdingerb** [comment]
> Perhaps this belongs in the User Guide, or Welcome manual?

This installation guide is already linked from the Installer page of the user guide when it points out how to add Haiku to Grub. Maybe we could make a more explicit mention of this guide.
We could also link to it from the Welcome page and rename the section "Update Haiku" to "Installing Haiku and updating". The updating part refers to Haiku itself and 3rd party software with SoftwareUpdater.

**Comment by humdingerb** [comment]
I made the above mentioned small changes to the Installer topic of the User Guide and the Welcome page at the online tool.
Merge.

**Pull request merged**
