### PR TITLE
Rewrite of "Make a Haiku USB stick" guide

### PR DESCRIPTION
**Pull request by humdingerb**
Not sure what css classes are around. There are the info boxes and pre.terminal, and I think the "button" is there... what about "menu", "cli", "path" from the user guide?

### CODE REVIEW

**Comment by waddlesplash** [comment]
Go ahead and merge whenever.

**Comment by humdingerb** [comment]
OK.
How about adding those user-guide stylings to the shijin4.css?

```
.menu {				/* Menu */
    	font-size: 1.0em;
    	font-family: serif;
    	font-style: italic;
	color: #24225e;
}
.button {			/* Button */
    	font-size: 1.0em;
    	font-family: serif;
    	font-style: italic;
	color: #33583c;
}
.app {				/* GUI Application name */
    	font-size: 1.0em;
    	font-family: serif;
    	font-style: italic;
	color: #5e1c1c;
}
.cli {				/* Shell command or file */
    	background-color: #e8e8e8;
    	font-size: 0.9em;
    	font-family: monospace;
}
.path {				/* File path */
    	background-color: #e8e8e8;
    	font-size: 0.9em;
    	font-family: monospace;
}
.key {				/* Shortcut (separate with   */
	-webkit-border-radius: 3px;
	-khtml-border-radius: 3px;
	-moz-border-radius: 3px;
	border-radius: 3px;
	border-color: #c7c7c7;
	border-style: solid;
	border-width: 1px;
	padding: 0px 2px 0px 2px;
	background-color: #e8e8e8;
    	font-family: serif;
   	font-variant: small-caps;
  	font-size: 0.8em;
}
```

(BTW, I'd like to use the "button" style of shijin4.css for the userguide css (with more horizontal padding)).

**Comment by pulkomandy** [comment]
> OK.
> How about adding those user-guide stylings to the shijin4.css?

+1. Userguide style everywhere!

**Comment by humdingerb** [comment]
I created #168 for adding the stylings. +1 or merge that one if everyone is on board.

**Comment by waddlesplash** [comment]
Merge?

**Comment by humdingerb** [comment]
After #168 was merged, I updated the PR with the new styles.
So, yes, please merge. I'd do it myself, but GitHub keeps insisting that it's still "Checking for ability to merge automatically…".

**Comment by humdingerb** [comment]
Oh, while your mind is on CSS... :)
Any opinion on https://www.freelists.org/post/haiku-web/Using-figurefigcaption-for-screenshot-heavy-guides ?

**Pull request merged**
