### PR TITLE
Edits to news item about repo changes

### PR DESCRIPTION
**Pull request by jt15s**
Added news item about the HaikuPorts issue and fixed a formatting issue with the last news item announcing the repo changes.

### CODE REVIEW

**Comment by kallisti5** [comment]
this one might be overkill? Not sure

**Comment by jt15s** [comment]
@kallisti5 Thought it might be good to let people know about the issue - it's a particularly important issue since HaikuPorts provides a lot of apps in Haiku. Additionally, I'm trying to issue more updates around these sorts of things, since it's always good to communicate with your users. :)

**Comment by kallisti5** [comment]
Sure, but the fix for the repo issue is the same as the haikuports issue.  I think we might be flooding folks with too much info since the issue is resolved?

Also, I noticed the last post had the commands to run "squished". https://www.haiku-os.org/news/2021-06-22_important_change_required_for_haiku_nightly_and_r1beta2_users/

I'd prefer fixing that one first :-)

**Comment by jt15s** [comment]
@kallisti5 I've fixed the issue with the squished commands in this PR as well.

**Comment by waddlesplash** [comment]
Yeah, this news seems superfluous. The problem was brief and is now resolved.

**Comment by jt15s** [comment]
I've done as you've suggested @waddlesplash and @kallisti5.

**Comment by jt15s** [comment]
@kallisti5 Can we merge this? It fixes the formatting issues and adds a notice about the issue with HaikuPorts.

**Comment by humdingerb** [comment]
Thanks!

**Pull request merged**
