### PR TITLE
Updated Xen tutorial screenshots

### PR DESCRIPTION
**Pull request by alwayslivid**
I recreated the screenshots that are currently (as of the time of this writing) present in the Xen virtualization tutorial, I...
- made a Xen development environment while I was [making sure that my own instructions were working as they should](https://github.com/haiku/website/pull/320) 
- took the screenshots carefully
- spent a lot of time editing them in GIMP in order to perfectly readjust the resolution and sort out the transparency.

Those screenshots were taken in a physical [Ubuntu Linux](https://ubuntu.com/) machine running the [Plasma Desktop](https://kde.org/plasma-desktop), accompanied by the [KWin](https://en.wikipedia.org/wiki/KWin) Window Manager.

### CODE REVIEW

**Comment by pulkomandy** [comment]
You have renamed the last two files, I think accidentally, and that would prevent them from showing in the article?

**Comment by alwayslivid** [comment]
> You have renamed the last two files, I think accidentally, and that would prevent them from showing in the article?

I reviewed my commit again and I have apparently made a small (but deadly) mistake and accidentally used the name "virtuaL_network_1.png" instead of "virtual_network_1.png". This concerns what's meant to be a single file.



Under ordinary circumstances, it would prevent the picture from showing in the article, considering that I did not change the `xen.md` file in any way.

The command `git mv ./static/files/guides/virtualizing/xen/virtuaL_network_1.png ./static/files/guides/virtualizing/xen/virtual_network_1.png` is a rough fix, but it should do the trick.

**Comment by alwayslivid** [comment]
I'll fix it myself in a bit.

**Comment by alwayslivid** [comment]
Fixed it, apologies for the delay. Feel free to merge the changes in one commit.

**Comment by humdingerb** [comment]
Thanks!

**Comment by humdingerb** [comment]
Thanks!

**Pull request merged**
