### PR TITLE
gsoc2022 introduction blog

### PR DESCRIPTION
**Pull request by MRNIU**
Signed-off-by: Zone.N <Zone.Niuzh@hotmail.com>

### CODE REVIEW

**Comment by MRNIU** [comment]
@scottmc @pulkomandy @davidkaroly

**Comment by pulkomandy** [comment]
Ok for me, I'll let the mentors review it in case there's something more to add

**Comment by davidkaroly** [comment]
basically lgtm

one minor thing: perhaps you could be a bit more specific with "run Haiku on ARM" - I assume it's the 32-bit ARM port and main target is running it in qemu? but better write it down explicitly...

**Comment by MRNIU** [comment]
> basically lgtm
> 
> one minor thing: perhaps you could be a bit more specific with "run Haiku on ARM" - I assume it's the 32-bit ARM port and main target is running it in qemu? but better write it down explicitly...

fixed

**Comment by MRNIU** [comment]
@pulkomandy maybe we can merge this?

**Pull request merged**
