### PR TITLE
Fixed the link to R1, Alpha 4.1

### PR DESCRIPTION
**Pull request by kneekoo**

### CODE REVIEW

**Comment by pulkomandy** [comment]
The current link points to https://www.haiku-os.org/get-haiku/release-r1a4 which is where Alpha 4.1 is downloadable.

**Comment by kallisti5** [comment]
Correct.  The latest release has it's own page since there are generally a bunch of mirrors where official releases can be downloaded.

**Comment by waddlesplash** [comment]
Closing as not-needed, then.

**Comment by kneekoo** [comment]
Someone fixed something in the backend, because yesterday the 4.1 link ended up in a 404.

**Pull request closed without merging**
