### PR TITLE
Get Haiku beta5 banner

### PR DESCRIPTION
**Pull request by humdingerb**
The "Download it now" banner for the front page.

DON'T MERGE UNTIL BETA5 HITS. :)

### CODE REVIEW

**Comment by humdingerb** [comment]
Lest we forget...

**Comment by waddlesplash** [comment]
I was just wondering about who would do this. Excellent!

I'll set it as a "draft", and will be sure to incorporate it into the final R1b5 merge PR...

**Comment by humdingerb** [comment]
👍

**Comment by waddlesplash** [comment]
Pulled the file into #608.

**Pull request closed without merging**
