### PR TITLE
development: Bootloader debugging with GEF

### PR DESCRIPTION
**Pull request by kallisti5**

### CODE REVIEW

**Comment by waddlesplash** [comment]
(I'd like to start moving a lot of these docs there too.)

**Comment by kallisti5** [comment]
https://www.haiku-os.org/documents/dev/ looks empty, am I missing something there?

**Comment by waddlesplash** [comment]
I said "in the tree" -- that is, `docs/develop/` in the Haiku repository.

**Comment by kallisti5** [comment]
oh.. ok.  We have a lot of trees :-D

**Comment by kallisti5** [comment]
put in docs/develop/kernel/boot in Haiku's sources

**Pull request closed without merging**
