### PR TITLE
Add news item celebrating 20 years of Haiku

### PR DESCRIPTION
**Pull request by jt15s**
Added a news item celebrating 20 years of Haiku, written by animortis with minor additions by me.

### CODE REVIEW

**Comment by korli** [comment]
Looks OK. An image with the news item would have helped "We're 20"

"This project wouldn't have been possible without the financial support of our donors, and is grateful to have their support."

A few quotes from the participants 20 years ago would have been nice, it might be too late for this.

**Comment by jt15s** [comment]
@korli I'm adding a line thanking donors, developers, and volunteers.

An image at the top of the article doesn't work unfortunately, since it won't render but I'll add a "baby photo" of Haiku (back when it didn't have a GUI) to end it. 

We do have plans to do some articles on the History of Haiku so we might get former developers/contributors to give an interview/provide quotes.

**Comment by jt15s** [comment]
Is this all good to merge now?

**Comment by aomgiwjc** [comment]
This will be great -- but the birthday is passing! Let us know what we can do to get this merged!

**Comment by korli** [comment]
> Is this all good to merge now?

it's good for me

**Pull request merged**
