### PR TITLE
Header and Footer Improvements

### PR DESCRIPTION
**Pull request by jt15s**
Added links to respective sidebar pages, plus added links to the bug tracker and HaikuDepot in the header. Also added links to the official Twitter, Mastodon and LinkedIn accounts in the footer (didn't include YouTube since that's inactive).

I merged the latest commits into this branch after uploading my work so if this needs to be redone let me know.

### CODE REVIEW

**Comment by panos** [comment]
Approving of this, I hope that my sins of including a URL in HTTP are forgiven.

**Comment by jt15s** [comment]
Haven't received a response from any of the website maintainers, so just wondering if this is all good to merge?

**Comment by pulkomandy** [comment]
"This branch cannot be rebased due to conflicts"

Please fix the merge conflicts.

**Comment by jt15s** [comment]
> "This branch cannot be rebased due to conflicts"
> 
> Please fix the merge conflicts.
Strange, it says on my end "This branch has no conflicts with the base branch". I've merged upstream with this branch to hopefully fix any conflicts.

**Pull request merged**
