### PR TITLE
Removed old tutorial succeeded by 'Building Haiku'

### PR DESCRIPTION
**Pull request by panos**

### CODE REVIEW

**Comment by pulkomandy** [comment]
Please replace it with a redirect to the new version. We don't like dead links :)

**Comment by panos** [comment]
> Please replace it with a redirect to the new version. We don't like dead links :)

Was very curious about this, how is that done?

**Comment by pulkomandy** [comment]
I don't know. Someone needs to read the Hugo documentation to find out.

**Comment by panos** [comment]
> I don't know. Someone needs to read the Hugo documentation to find out.

Guess that has to be me, will do! (sorry!)

**Comment by panos** [comment]
- [Here's how Haiku does it.](https://github.com/haiku/website/blob/master/static/_redirects)
- [Here's the Hugo documentation](https://gohugo.io/content-management/urls/)

Seems like that hasn't quite happened in the `content` section before, is it safe to move forward?

**Comment by pulkomandy** [comment]
Yes, no one has dared to touch the website organization for the last 10 years and it is more than time to do something about it.

**Comment by leavengood** [comment]
Netlify handles the `_redirect` file for us, and that seems fine for now. Maybe using Hugo features is also an option but that does not need to hold this up. Please just add a redirect for this to the proper location. It seems the URL for this is `https://www.haiku-os.org/documents/dev/building_haiku_ubuntu_linux_step_step/`

**Comment by waddlesplash** [comment]
https://github.com/haiku/website/commit/aed44796fea18a780774d286d2e415b2210ab1bf

**Pull request closed without merging**
