### PR TITLE
Replace gcc11 with gcc13 where appropriate

### PR DESCRIPTION
**Pull request by korli**

### CODE REVIEW

**Comment by diversys** [comment]
There seems to be still some references to gcc8

**Comment by korli** [comment]
> There seems to be still some references to gcc8

You mean in the blogs? These shouldn't be updated.

**Comment by diversys** [comment]
Seems not only the blogs:
```
grep -rnIi gcc8
content/blog/pulkomandy/2018-07-30_haiku_monthly_activity_report_july_2018.md:73:<h3>Switching to gcc8 (WIP)</h3>
content/guides/building/compiling-x86_64.md:15:x86_64 exclusively uses gcc8, this differs from our 32-bit x86_gcc2 builds which
content/guides/building/compiling-x86_64.md:16:include both gcc2 (for BeOS compatibility) and gcc8 as a secondary architecture.
content/guides/building/compiling-x86.md:8:<h3>gcc2h / gcc8 hybrid builds</h3>
content/guides/building/compiling-x86.md:11:as gcc8 binaries. More information on this can be found on the <a href='/guides/building/gcc-hybrid'>gcc-hybrid</a> page.</p>
content/guides/building/gcc-hybrid.md:10:Haiku hybrid images are Haiku releases which can compile and execute programs built for incompatible ABIs. This may mean different architectures like x86-64 and x86, or different, incompatible compilers like gcc2.95 and gcc8.x for x86. Currently only the latter case is supported. gcc2.95 gives Haiku binary compatibility with native legacy applications written for the BeOS.
content/guides/building/gcc-hybrid.md:18:The architecture name used in the build system and in Haiku for x86 gcc2 is "x86_gcc2" and for x86 gcc8 "x86". In a Haiku Hybrid one can find subdirectories named like the secondary architecture in */lib/, */bin/, and other directories. They contain files specific to the secondary architecture portion of the Hybrid.
content/guides/building/gcc-hybrid.md:27:In short, a gcc2 Hybrid. For R1 and earlier releases, gcc2 Hybrid is the official release style. As such you can expect the least amount of issues on it. Later we will likely switch to gcc8 Hybrids and eventually phase out the gcc2 part completely.
content/guides/building/gcc-hybrid.md:30:<h3>Why not gcc8?</h3>
content/guides/building/gcc-hybrid.md:32:For R1 and earlier releases, only the gcc2 ABI can be considered stable and future proof. Once R1 is released, binaries built with gcc8 will need to be recompiled (and more than likely have their sources updated for new API).
```

**Comment by korli** [comment]
it would have been better to squash the commits...

**Pull request merged**
