### PR TITLE
blog/dominicm: GSoC 2022 Ham Final Report

### PR DESCRIPTION
**Pull request by dominicm00**
I'm opening this as a draft so it's ready to go pending a final review.

### CODE REVIEW

**Comment by pulkomandy** [comment]
Looks good to me, @stippi do you have any comments?

For the GSoC final work submission, please set a git tag with the code in the state at the end of GSoC, and point this blogpost to it. Then you can submit the blogpost as your final report.

This makes sure we have a long-term URL to the work done specifically for GSoC, even if more work happens on ham later. Google requires something like that so they can know what code was produced during GSoC (mainly to check we are producing actual work with their money).

**Comment by dominicm00** [comment]
> For the GSoC final work submission, please set a git tag with the code in the state at the end of GSoC, and point this blogpost to it. Then you can submit the blogpost as your final report.

Thanks for the note; I included commit information and also tagged the repo.

**Comment by dominicm00** [comment]
Also, please make sure to keep the file name the same since I'm submitting the link! This is the link I am submitting: https://www.haiku-os.org/blog/dominicm/2022-09-10_gsoc_2022_ham_final_report/

**Comment by dominicm00** [comment]
If the date has to be changed please let me know before the deadline

**Pull request merged**
