### PR TITLE
Create 2021-06-14_haiku_r1beta3_timeline_approved.md

### PR DESCRIPTION
**Pull request by jt15s**
Added news item announcing the release timeline for Beta3.

### CODE REVIEW

**Comment by pulkomandy** [comment]
Do we need someone to step up as release coordinator before we officially launch this?

**Comment by jt15s** [comment]
> Do we need someone to step up as release coordinator before we officially launch this?

@kallisti5 said on the mailing lists that he can be the release coordinator, though currently, no one has stepped up to fill the secondary/backup release coordinator role.

**Comment by jt15s** [comment]
By the way, @pulkomandy, could you please have a look at #511? I haven't received a response from any of the website maintainers on whether this is okay to merge or not. Thanks in advance!

**Comment by pulkomandy** [comment]
I am not specifically a website maintainer. My intervention should not be required and it is very annoying for me to be in charge of everything. Can you please find someone else to ask?

Also, if you want to ping me about another merge request, please do so in that merge request and not here. This is just polluting comments about unrelated things.

**Comment by jt15s** [comment]
> I am not specifically a website maintainer. My intervention should not be required and it is very annoying for me to be in charge of everything. Can you please find someone else to ask?
> 
> Also, if you want to ping me about another merge request, please do so in that merge request and not here. This is just polluting comments about unrelated things.

Sorry about that!

**Comment by kallisti5** [comment]
Lets not post the exact timeline in duplicate of the wiki.  Timelines to release tend to slide.   Posting our tentative target date seems fine though (linking to the wiki)

**Comment by jt15s** [comment]
@kallisti5 How's this?

**Comment by kallisti5** [comment]
Looks good to me :-)

**Pull request merged**
