### PR TITLE
Date fixes and new blogpost

### PR DESCRIPTION
**Pull request by CruxBox**

### CODE REVIEW

**Comment by pulkomandy** [comment]
It looks like you are re-adding your previous post? Why is that?

**Comment by CruxBox** [comment]
> It looks like you are re-adding your previous post? Why is that?

Hey, the previous post had the date wrong. So I changed it.

**Comment by pulkomandy** [comment]
You added a second copy of it.  think it's better to fix the date in the header of the file, but not rename the file with the new date. That's because the filename is visible in the url, and moving that will create deadlinks (in the forum thread with comments about the post, for example)

**Comment by CruxBox** [comment]
I messed up my local a bit. I'll create a new PR.

**Pull request closed without merging**
