### PR TITLE
Add meta image for social media

### PR DESCRIPTION
**Pull request by kainjow**
Fixes Trac [#11605](https://dev.haiku-os.org/ticket/11605)

### CODE REVIEW

**Comment by pulkomandy** [comment]
Why should we use this unofficial logo here?
Official things from the Haiku project should use the registered logo: http://haiku-inc.org/logo-design-details.html

**Comment by drawkula** [comment]
For me the leaf looks unrelated to the "twin towers" in the background.
I've not a good feeling when watching this...

**Comment by kainjow** [comment]
I just used what was suggested in Trac.

How about this one? I used the svg logo from the website, and used #3B5378 as the bg color as the website also uses. The size is also what Facebook suggests for a minimum.

haiku_600x315

**Comment by pulkomandy** [comment]
Yes, that would be better.
And for a more square logo, I would rather use https://www.haiku-os.org/files/haiku-sticker-preview.png or a derivative (we have SVG sources for it if we want to make changes)

**Comment by drawkula** [comment]
This one does not give me the "twin towers" association.
Probably because of being in context with more other chars.

**Comment by kainjow** [comment]
If that logo is unofficial why is it used on the Haiku GitHub [profile](https://github.com/haiku) or on the top right of [download.haiku-os.org](http://download.haiku-os.org)?

**Comment by pulkomandy** [comment]
There is a single official registered logo. The other one is the Haiku3D icon with a blue frame around it, and was never made official. I have no idea why people started using it everywhere. Maybe just because of its aspect ratio when a "mostly square" one is required?

**Comment by humdingerb** [comment]
On 27 February 2017 at 07:12, Adrien Destugues <notifications@github.com>
wrote:

> Maybe just because of its aspect ratio when a "mostly square" one is
> required?


Exactly. Hey, you sat beside me when we did just that for an icon for the
Flare game's website (1). :)
Using the official "Haiku" doesn't really work well and using just the "H"
looks a bit barren compared to the oter OS' logos.

Regards,
Humdinger

(1) http://flarerpg.org/

--
Did you know:
  If half the Haiku supporters at http://www.goodsearch.com
  made 10 searches a day, we could have a fulltime developer.

**Comment by pulkomandy** [comment]
but the 3D logo can also stand out a little too much in these flat design days: https://pytouhou.linkmauve.fr/index.fr.xhtml

I think something based on the sticker, maybe on a white background, could work. Koki had made several variants of that sticker design but the draft sheets are lost now. So we would need to re-derive them from the SVG.

Anyway, maybe we should discuss this elsewhere?

**Comment by humdingerb** [comment]
On 27 February 2017 at 08:33, Adrien Destugues <notifications@github.com>
wrote:

> So we would need to re-derive them from the SVG.


I only see one sticker design recently added to the artwork folder. I'll
try to recreate that one with WonderBrush first.

Regards,
Humdinger

--
Did you know:
  If half the Haiku supporters at http://www.goodsearch.com
  made 10 searches a day, we could have a fulltime developer.

**Comment by waddlesplash** [comment]
This PR looks good to me now. Merge?

**Comment by kainjow** [comment]
Looks like this has fallen off the radar. Any further feedback?

**Comment by waddlesplash** [comment]
No replies from the others, so I'll merge anyway.

**Pull request merged**
