### PR TITLE
General cleanup

### PR DESCRIPTION
**Pull request by jt15s**
Redid this PR since the last PR was based on an older version of the file. Fixed typos, rewrote sentences for clarity, added one or two alert boxes and moved headings up by one since H2 wasn't being used.

### CODE REVIEW

**Comment by pulkomandy** [comment]
I had already commented on your previous PR but my comment has apparently been ignored?

The headers on the website content start at h3 everywhere. h2 is used for the article title.

**Comment by pulkomandy** [comment]
Also, the application period for GSoC is now closed and this page should be kept as it is for archival. We can integrate your changes in the version for 2022.

**Comment by jt15s** [comment]
> I had already commented on your previous PR but my comment has apparently been ignored?
> 
> The headers on the website content start at h3 everywhere. h2 is used for the article title.

Sorry, I thought that comment was just a remark, not a suggestion to use the same heading structure as the rest of the site. I will revert back to the original heading structure.

**Comment by jt15s** [comment]
> Also, the application period for GSoC is now closed and this page should be kept as it is for archival. We can integrate your changes in the version for 2022.

Ah okay, I will close this PR then, but I'll keep the branch so once the 2022 pages are created I can copy+paste the file on my branch over to the 2022 pages. What do you think?

**Comment by leavengood** [comment]
Yes let's maybe apply some of these changes in 2022.

**Pull request closed without merging**
