### PR TITLE
 Update compiling-86.md to note that xorriso is now required and not integrated

### PR DESCRIPTION
**Pull request by Coldfirex**
https://dev.haiku-os.org/ticket/17161
https://discuss.haiku-os.org/t/xorriso-requirement-when-building-haiku/11173

### CODE REVIEW

**Comment by Coldfirex** [comment]
I wish I knew why it shows my old files in this pull request that were already merged.

**Comment by jt15s** [comment]
@Coldfirex Hey there, this happened to me when I first started contributing to the Haiku website as well. 
You're working off the master branch of your fork of the website, but the thing I learnt was better is to create a new branch every time you work on the website, create a PR of that branch, and then delete the branch when the PR is merged. That way all your previous commits don't get merged every time you try to merge something new into the website. Hope this helps!

**Comment by Coldfirex** [comment]
> 
> 
> @Coldfirex Hey there, this happened to me when I first started contributing to the Haiku website as well.
> You're working off the master branch of your fork of the website, but the thing I learnt was better is to create a new branch every time you work on the website, create a PR of that branch, and then delete the branch when the PR is merged. That way all your previous commits don't get merged every time you try to merge something new into the website. Hope this helps!

Thanks!  I will try that.  Do we want to kill this PR and start over then?

**Comment by jt15s** [comment]
@Coldfirex Yeah, might be a good idea.

**Pull request closed without merging**
