### PR TITLE
Adding Haiku to the Windows boot menu using EasyBCD

### PR DESCRIPTION
**Pull request by khallebal**
@humdingerb  how do i add screenshots and link a url to text?
Nevermind i found how to add them.

Is there a way to test the changes localy?

### CODE REVIEW

**Comment by diversys** [comment]
For some reason the screenshots look very blurry. And the blue selection loop should be probably replaced with something nicer lookng?

**Comment by khallebal** [comment]
Thanks for replying, the shots look sharp when open them in haiku and windows, it could be a rendering issue? i don't what to do to test everything localy, any tip? as for the the blue selection, i'm open to suggestions.
Regrads.

**Comment by waddlesplash** [comment]
Screenshots don't really look blurry here. But yeah, the selection probably could be improved.

**Comment by khallebal** [comment]
> But yeah, the selection probably could be improved.

Oh you probably mean the shapes?, yeah it's difficult to do with the mouse, i'll try to make better ones.

**Comment by khallebal** [comment]
I have updated the shots, please review.

**Comment by waddlesplash** [comment]
Thanks!

**Pull request merged**
