### PR TITLE
Add post showing icon sets proposed in icon set contest

### PR DESCRIPTION
**Pull request by Zardshard**

### CODE REVIEW

**Comment by humdingerb** [comment]
Theres a stray file static/files/blog/zardshard/icon_sets/out-0 there that's the same as 575.png.

**Comment by Zardshard** [comment]
Good catch!

**Comment by pulkomandy** [comment]
I did some mailing list archive digging.

The contest was announced here: https://www.freelists.org/post/haiku/Icon-Artwork,11

The discussion and submissions continue for a few months (06/2006 to 11/2006) but there is a convenient summary thread once a winer has been picked: https://www.freelists.org/post/haiku/Icons-summery-of-past-discussions

Maybe these links can be added to the blogpost so we don't have to do the digging again

**Comment by Zardshard** [comment]
Nice! I also included some changes I wanted to make.

**Pull request merged**
